### ISSUE TITLE
Action never fails

### ISSUE THREAD

**Issue by kojofosu-ghyrate** [marcodallasanta/ssh-scp-deploy#12]
When there is an error transferring file over scp,  the action does not fail

**Comment by marcodallasanta** [comment]
Hi @kojofosu-ghyrate , could you please add your configuration to reproduce this?

**Comment by kojofosu-ghyrate** [comment]
<img width="651" alt="scp-deploy" src="https://user-images.githubusercontent.com/69309530/132494151-32c828fb-31bb-47b7-a8bd-3c8783fe13da.PNG">

Its clear the transfer was not successful but then it does not fails. The action itself

**Comment by marcodallasanta** [comment]
Ok surely this is a bug and will be solved in the next release. Thanks for helping me discover this! 🚀
